plots:
   - Confusion matrix:
        template: confusion
        x: actual
        y:
          training/plots/sklearn/confusion_matrix.json: predicted
stages:
  prepare_data:
    cmd: python prepare_data.py
    deps:
    - prepare_data.py
    - data/raw.csv
    outs:
    - mobile_data.csv
  train:
    cmd: python train.py
    deps:
    - train.py
    - mobile_data.csv
    
    metrics:
    -  metrics.json:
          cache: false
