name: mobile-price-classification
on: [push]
jobs:
  build:
  
        runs-on: ubuntu-latest
        strategy:
          matrix:
            python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

        steps:
          - uses: actions/checkout@v3
          - name: Set up Python ${{ matrix.python-version }}
            uses: actions/setup-python@v4
            with:
              python-version: ${{ matrix.python-version }}
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install ruff pytest
              if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          - name: Lint with ruff
            run: |
              # stop the build if there are Python syntax errors or undefined names
              ruff --format=github --select=E9,F63,F7,F82 --target-version=py37 .
              # default set of ruff rules with GitHub Annotations
              ruff --format=github --target-version=py37 .
          - name: Test with pytest
            run: |
              pytest
              
          - uses: iterative/setup-cml@v1
          
          - name: Train model
            env:
              REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            run: |
              pip install -r requirements.txt
              dvc repro
              git fetch --prune
              dvc metrics diff --show-md main > report.md


              # Publish confusion matrix diff
              echo "## Plots" >> report.md
              echo "### Class confusions" >> report.md
              dvc plots diff --target classes.csv --template confusion -x actual -y predicted --show-vega main > vega.json
              vl2png vega.json -s 1.5 > confusion_matrix.png
              echo "![](./confusion_matrix.png)" >> report.md

              cml comment create report.md
